### ISSUE TITLE
Feedback and questions

### ISSUE THREAD

**Issue by nianzelee** [NTU-ALComLab/LSV-PA#143]
Dear Students,

Now that the submission period of parts 1 and 2 for PA1 is over,
I would like to invite you to give your feedback or ask questions about the submission workflow.
Please speak up. Your comments are cordially welcome.
Depending on your response, we may allocate an additional hands-on session to help you with the PAs.

**Comment by bohamfu** [comment]
Dear nian ze,

助教您好,這是我第一次使用這樣的系統與語言方式

有些操作上的問題 想請教您

是否有開放TA時間方便當面去研究室請教呢?謝謝

**Comment by nianzelee** [comment]
Hi, thanks for the feedback.
Yes there is a plan to host a hands-on session to answer your questions.
Let's wait for others to speak up and decide the time.

**Comment by nianzelee** [comment]
Things I want to mention:
- issue tracker and watch
- good practices about git
- `.gitignore` file and external packages
- continuous integration

**Comment by nianzelee** [comment]
Next time let's allocate a dry-run submission period to test your pull requests and to avoid last-minute panic.
