### ISSUE TITLE
Nodes with zero fanins

### ISSUE THREAD

**Issue by Luo-Yun-Rong** [NTU-ALComLab/LSV-PA#150]
助教您好，

我測試benchmark時，用範例command: "lsv_print_nodes" 時會遇到這種node
`Object Id = 61, name = n61
The SOP of this node:
 1
`
看起來應該是constant 1, 請問對於這種node我們應該怎麼處理呢?
請問是比照absent-variable 的處理方式嗎？這樣這個node的fanin就是所有PI嗎？

謝謝助教！

**Comment by nianzelee** [comment]
Hi, thanks for opening the issue.

You only need to print the unate information for the **fanins** of the node.
If a node has no fanin, just skip it.

(In the absent-variable case, the absent variable is explicitly listed as a fanin of the node in the blif file.
Therefore we have to print the unate information of it.)

**Comment by Luo-Yun-Rong** [comment]
所以是連node xxx: 這行都直接不印嗎？(zero  fanin的node)

**Comment by nianzelee** [comment]
Yes, skip the line `node CONST1:`.
