### ISSUE TITLE
A reference program and a grading script

### ISSUE THREAD

**Issue by nianzelee** [NTU-ALComLab/LSV-PA#152]
I just pushed a [reference program](https://github.com/NTU-ALComLab/LSV-PA/blob/master/pa1-ref.zip) for PA1 and a [grading script](https://github.com/NTU-ALComLab/LSV-PA/blob/master/lsv/admin/grade-submissions.sh) that will be used to grade your solutions.

The reference program is compiled under Ubuntu 20.04 and `libreadline8`.
It has to be zipped otherwise it exceeds the file size limit (100 MB) of GitHub.

The grading script compares the outputs produced by the reference program and a student's program.
The usage of the script is:
```
Usage: ./lsv/admin/grade-submissions.sh <ALL|branch-name>
ALL: grade ALL students
branch-name: the branch to grade, e.g., d04943019
```
If your code is in `master`, just type `./lsv/admin/grade-submissions.sh master`

The comparison is done by `diff -uwiB <ref.txt> <out.txt>`, which ignores all white space, blank lines, and case differences.
We will use 40 test cases from the EPFL benchmark suite at tag `v2020.1`.
Two points will be given if the return code of `diff` equals 0.
For the script to find the test cases, you have to create a symbolic link to the EPFL benchmark suite as described [here](https://github.com/NTU-ALComLab/LSV-PA/blob/master/README.md#evaluation).

You are encouraged to test your solution, and please speak up if there is any problem.

**Comment by nianzelee** [comment]
Two additional binaries have been uploaded:
- [`pa1-ref-mac`](https://github.com/NTU-ALComLab/LSV-PA/blob/master/pa1-ref-mac.zip) (compiled in MacBook) 
- [`pa1-ref-libreadline7`](https://github.com/NTU-ALComLab/LSV-PA/blob/master/pa1-ref-libreadline7.zip) (compiled with `libreadline7`)

Remember to rename the binary to `pa1-ref` after you unzip the archive. Otherwise the grading script cannot work.

In case you cannot execute any of the provided binaries, please let me know.

**Comment by ian861226** [comment]
助教你好,

想確認一下執行方式是解壓縮後 ./pa1-ref嗎?
我執行時出現
`error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory`
而改成用libreadline7版本時會出現
`error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory`
LSV-PA下都沒有這兩個檔案
想請問助教我哪邊做錯了或要怎麼解決?

謝謝!

**Comment by nianzelee** [comment]
What is the version of your OS and `libreadline-dev`?

**Comment by ian861226** [comment]
OS版本是CentOS Linux release 7.3.1611 (Core)
請問`libreadline-dev`的版本要怎麼看?

**Comment by nianzelee** [comment]
`yum info readline`

**Comment by ian861226** [comment]
看起來是6.2

**Comment by nianzelee** [comment]
Yes, that is the problem. I don't have access to such systems.
Is it possible for you to upgrade libreadline?

**Comment by nianzelee** [comment]
I will try to compile a binary without `libreadline`.

**Comment by nianzelee** [comment]
I will first push some reference answers for you to check the outputs of your program.

**Comment by ian861226** [comment]
Thanks for help!

**Comment by nianzelee** [comment]
@ian861226 Could you please report if the `pa1-ref-no-readline` one or `pa1-ref-libreadline6` work for you?

**Comment by ian861226** [comment]
`pa1-ref-no-readline` 可以使用!

**Comment by nianzelee** [comment]
What error messages did you get for `pa1-ref-libreadline6`?

**Comment by ian861226** [comment]
`pa1-ref-libreadline6`也沒問題

**Comment by roberthuang0306** [comment]
我剛剛在跑 grading script 的時候發現，如果是執行
`sh ./lsv/admin/grade-submissions.sh master`
的話，會一直跳
`./lsv/admin/grade-submissions.sh: 14: Syntax error: "(" unexpected`
但是，
`bash ./lsv/admin/grade-submissions.sh master`
的話就可以執行...

我的OS是 ubuntu 20.14 
因為剛剛卡很久，想說丟上來讓跟我卡一樣地方的人知道一下

**Comment by nianzelee** [comment]
> 我剛剛在跑 grading script 的時候發現，如果是執行
> `sh ./lsv/admin/grade-submissions.sh master`
> 的話，會一直跳
> `./lsv/admin/grade-submissions.sh: 14: Syntax error: "(" unexpected`
> 但是，
> `bash ./lsv/admin/grade-submissions.sh master`
> 的話就可以執行...
> 

Hi, good observation.
Yes, the script requires `bash`.
Actually you can just run `./lsv/admin/grade-submissions.sh master` without `sh` or `bash`.
The default script interpreter on Ubuntu 20.04 is `bash`.

I will add a preamble to the script to force the OS to interpret it with `bash`.

**Comment by Runnlion** [comment]
您好助教，我想請教一下在做運行grade_submission這個文件的時候，有沒有需要注意到的部分，例如在這個blif中
.names a b c-in sum #sum=XOR(a,b,c-in)
100 1
010 1
001 1
111 1
.names a b c-in c-out #c-out=MAJ(a,b,c-in)
11- 1
1-1 1
-11 1
.end
我的程式輸出以下内容
node sum
+unate inputs: 
-unate inputs: 
binate inputs: a  b  c-in  
node c-out
+unate inputs: a  b  c-in  
-unate inputs: 
binate inputs:

我試過一些例子，得到的answer手動驗證都是正確的
但是運行.sh 文件的時候，卻得到correct case 為0的result

期待回復！

**Comment by nianzelee** [comment]
> 我的程式輸出以下内容
> 
> ```
> node sum
> +unate inputs: 
> -unate inputs: 
> binate inputs: a  b  c-in  
> node c-out
> +unate inputs: a  b  c-in  
> -unate inputs: 
> binate inputs:
> ```

The grading script runs `diff` to decide whether your output is identical (**verbatim!**) to that of the reference program.
In the above example, you printed lines without any input, and the delimiter between inputs should be a comma.
After executing the grading script, you can check the directory `lsv/pa1/diff` for the difference.

**Comment by Runnlion** [comment]
Thank you TA.
I have fixed that problem.
but I just encountered another problem when benchmarked my code.
`find: ‘benchmarks/best_results/’: No such file or directory
fatal: invalid reference: master
`
In the terminal the two line shown, and I can not get the diff value whatever it is right or wrong.
How can I fix that problem?
Hoping for your reply.

**Comment by nianzelee** [comment]
> `find: ‘benchmarks/best_results/’: No such file or directory`

For the script to find the test cases, you have to create a symbolic link to the EPFL benchmark suite as described [here](https://github.com/NTU-ALComLab/LSV-PA#evaluation).

**Comment by TZU-MIAO** [comment]
助教你好
下載pa1-ref-mac
執行後
abc 01> ./lsv/admin/grade-submissions.sh master
跑出了這些，不知道怎麼解決
** cmd error: unknown command './lsv/admin/grade-submissions.sh'
(this is likely caused by using an alias defined in "abc.rc"
without having this file in the current or parent directory)
