### ISSUE TITLE
How to obtain an AIG circuit (Aig_Man_t) from a network (Abc_Ntk_t)

### ISSUE THREAD

**Issue by david057178-2020** [NTU-ALComLab/LSV-PA#211]
助教您好

我在第一個問題就卡關了QQ
面對像abc這樣龐大的project，trace code時要如何有效率地去找到某個特定的API呢?
以我現在面對的問題為例，我只能猜應該有一個function是把Abc_Ntk_t*當作input，Aig_Man_t*當作output，但是如果用grep針對這兩個關鍵字下去找，會找到一堆無關緊要的東西。而我去看了定義Abc_Ntk_t跟Aig_Man_t這兩個struct的檔案，找到的也都是我能用它來做什麼，而不是我該如何得到它。想知道未來面對類似的問題，該如何有效率地去找到某個特定的API。

謝謝解惑

**Comment by nianzelee** [comment]
I would say there is probably no silver bullet to this problem.
This depends on your experience with the project.
To gain experience, I would suggest to trace the code of a component which is similar to your goal.

In our cases, I recommend you to start with command `dsat`.
This command takes as input a single-output network (`Abc_Ntk_t`), converts it to an AIG (`Aig_Man_t`), and tests whether the output can be evaluated to true by SAT solving.
Most necessary APIs for PA2 are covered in this command.

**Comment by david057178-2020** [comment]
助教您好

謝謝您的回覆
我原先誤解了在wiki中要我們看dsat的用意(我以為是run abc然後跑這個指令)
我會試著看這個指令相關的code implementation
謝謝
