### ISSUE TITLE
得到single output的cnf

### ISSUE THREAD

**Issue by david057178-2020** [NTU-ALComLab/LSV-PA#212]
助教您好

目前我知道如何透過Abc_Ntk_t得到Aig_Man_t，並由Aig_Man_t得到Cnf_Dat_t
但是上述的Cnf_Dat_t是把所有的clause全部混在一起(變成一個大的muti-output circuit)，而PA2應該是要針對每個PO個別處理(拆成許多小的single output circuit)，因此我必須要得到single output的Cnf

由Abc_Ntk_t可以得到每一個PO node(type是Abc_Obj_t)
由Aig_Man_t也可以得到每一個PO aig node(type是Aig_Obj_t)
但是似乎沒有API可以從上述的PO Abc_Obj_t或Aig_Obj_t變成Cnf_Dat_t?
如果想得到single output的cnf，是不是要參考如Cnf_Derive這樣的function，自己寫一個類似的function，針對每個PO node DFS轉成CNF呢?

因為感覺是個不小的工程，因此想先確認一下我的想法是不是有錯
謝謝助教解惑

**Comment by nianzelee** [comment]
You could take a look at function `Abc_NtkCreateCone()`, which extracts the TFI cone (type `Abc_Ntk_t`) of a given node (type `Abc_Obj_t`). After obtaining a single-output circuit, you can pass it to `Cnf_Derive()`.

Reminder: Be careful with `Abc_NtkCreateCone()`. The returned network might have a different order of PIs and the PO might not be negated correctly. Have a look at command `cone` for more details.
