### ISSUE TITLE
PA2 reference program and updated grading script

### ISSUE THREAD

**Issue by nianzelee** [NTU-ALComLab/LSV-PA#213]
A [reference program](https://github.com/NTU-ALComLab/LSV-PA/blob/master/pa2-ref.zip) (zipped due to the file size limit of GitHub) and an updated [grading script](https://github.com/NTU-ALComLab/LSV-PA/blob/master/lsv/admin/grade-submissions.sh) have been published.

In order to save the time to grade your submissions, the [reference outputs](https://github.com/NTU-ALComLab/LSV-PA/tree/master/lsv/pa2/ref) of the selected test cases were also published.
The updated grading script does **NOT** invoke the reference program.
Instead, it only invokes your submission and compares the outputs to the reference answers.

**Comment by nianzelee** [comment]
Please note that your branch has been synchronized with the master branch.
Therefore, the simplest way to obtain the above updates is to synchronize your local branch with the upstream branch (i.e., the branch with your student ID number).

**Comment by nianzelee** [comment]
A reference program for macOS will be published later.

**Comment by nianzelee** [comment]
Two additional reference programs for Ubuntu-18.04 and macOS have been published.
(The original reference program is for Ubuntu-20.04.)

**Comment by qmo1222** [comment]
The grading script causes "timeout: failed to run command ‘abc’: No such file or directory".
I solved it by modifying the line 46 in [grading script](https://github.com/NTU-ALComLab/LSV-PA/blob/master/lsv/admin/grade-submissions.sh), replacing "abc -c ....."  with "./abc -c .....".
Hope this may help some classmates.

**Comment by nianzelee** [comment]
Thanks for pointing this out. You can also append the current directory to the search path for executable files by adding `export PATH=$PATH:.` in your `.bashrc`.

**Comment by nianzelee** [comment]
> The grading script causes "timeout: failed to run command ‘abc’: No such file or directory".
> I solved it by modifying the line 46 in [grading script](https://github.com/NTU-ALComLab/LSV-PA/blob/master/lsv/admin/grade-submissions.sh), replacing "abc -c ....." with "./abc -c .....".
> Hope this may help some classmates.

Thanks for pointing this out. You can also append the current directory to the search path for executable files by adding `export PATH=$PATH:.` in your `.bashrc`.

I have updated the grading script to avoid confusion.
