### ISSUE TITLE
sat_solver_add_buffer_enable() enabling variable

### ISSUE THREAD

**Issue by roberthuang0306** [NTU-ALComLab/LSV-PA#216]
想請問助教sat_solver_add_buffer_enable() 之中enabling variable的功能。
我的理解是enbling variable ==1的時候，iVarA 和iVarB 會被控制成equivalent。
因此在這次作業之中，所有的enbling variable 都應該被設為1。
想請問助教我的理解是否錯誤？

**Comment by nianzelee** [comment]
@roberthuang0306 Would you please share your findings so that other students can learn from them?

**Comment by roberthuang0306** [comment]
喔好～
大部分的情況應該都要將enabling varible 設成1，也就是toLitCond(enabling_varible, 0)
只有在要控制某一個PI時（也就是要對他做cofator時）才要將相對應的enabling varible設成0，因為之後那個PI在sat solver之中的兩個circuits 的值會不一樣（一個是positive cofactor, 一個是negative cofator）。
大概是這樣，如果我的理解有錯助教可以再提醒！！謝謝助教
