### ISSUE TITLE
Rearrange the directory structure

### ISSUE THREAD

**Issue by nianzelee** [NTU-ALComLab/LSV-PA#285]
I would like to suggest rearranging the current directory structure, in order to avoid duplication and confusion.

I propose to have only one `lsv` folder, instead of having both `lsv` from last year and `lsv_fall_2021` for this year.
We could create a folder named `archive` under `lsv` and put the old PA folders inside it.
The `admin` folder would remain the same, except for an updated student list `participants-id.csv`.
The `example` folder also stays there, because the Wiki pages link to those files.

@Luo-Yun-Rong What do you think?

**Comment by Luo-Yun-Rong** [comment]
Thanks for the suggestion. I'' first rename the original `lsv` directory as `archive`. Since we've already announced the HW spec, and we are going to explain it in the next hr, maybe it is better to temporarily keep ` lsv_fall_2021` for this semester, and I'll update them after the semester ends.

**Comment by nianzelee** [comment]
Sure, if this fits your teaching plan. But please remember that it is good to avoid duplicate or very similar names, files, functions, etc. They are confusing to users and incur additional maintenance costs.

**Comment by Luo-Yun-Rong** [comment]
Many thanks.

**Comment by nianzelee** [comment]
Let's keep this issue open as a reminder to implement the change.

**Comment by nianzelee** [comment]
Commit 92ab2b1 closes this issue.
