### ISSUE TITLE
Some ABC commands are not supported.

### ISSUE THREAD

**Issue by HeHH1329** [NTU-ALComLab/LSV-PA#335]
Hi everyone, 
I just found that some commands listed on the official [ABC manual](https://people.eecs.berkeley.edu/~alanmi/abc/) such as write_counter or sec are actually not supported by ABC. 
The error message cmd error: unknown command keeps popping up whenever I input these commands.
The problem exists for both the ABC provided in this course or the version from the official github repository.
Is the manual wrong or did I downloaded the wrong version? Thanks.

**Comment by Luo-Yun-Rong** [comment]
I think the manual has not been updated for a while. ABC is not well documented, so I think maybe it is not the best way to understand its functions by searching for documents. 

You can run `help` in ABC's command line. It will list all the commands. If you want to see the description of  command `cec`, you can run `cec -h`. If you are still confused, then tracing the code of the command is the best way to understand it. The starting point of tracing a command is `src/base/abci/abc.c`

If you want to find commands that do sequential equivalence checking (SEC), a tip for you is to "grep" the string.
For example,  you can run the following linux command in `src/`
```
$ grep -r "sequential equivalence checking" ./
```
It will recursively search for the pattern "sequential equivalence checking" in `src/`. Similarly, you can also grep `SEC` ...

We always synchronize our repository with Berkeley ABC, so there is no need to check both versions.

**Comment by nianzelee** [comment]
I agree with Yun-Rong: The documentation is not up to date and it is not a good idea to completely rely on it.

>  We always synchronize our repository with Berkeley ABC, so there is no need to check both versions.

Exactly.
