### ISSUE TITLE
what kind of representation should we expect in PA1 part 3?

### ISSUE THREAD

**Issue by mirkat1206** [NTU-ALComLab/LSV-PA#394]
There are different ways to represent Boolean functions in ABC. ex: aig, strash, bdd, ...

In PA1_README, "Write a procedure in ABC that ﬁnd maximum single-fanout cones (MSFCs) that covers all nodes (excluding PIs and POs) of a given ****AIG****."
Since the picture in PA1_README can only be seen after "strash" command, does it mean that the network would be executed by "strash" before being executed by  "lsv_print_msfc"?
![圖片](https://user-images.githubusercontent.com/55183618/136569151-09ace3d5-7bc1-4e78-8b1a-c0a899c17792.png)

i.e. when we try to test our procedure ourselves by a BLIF file, should we first "read", then "strash" to make it AIG, and then "lsv_print_msfc"?

**Comment by Luo-Yun-Rong** [comment]
You can assume we will only use *.aig as test cases.
I remembered that ABC strashes AIGs  in `read`, so you don't need to run `strash` again.
In your command, after retrieving `pNtk` by
```
Abc_Ntk_t* pNtk = Abc_FrameReadNtk(pAbc);
```
You can assert this:
```
assert(  Abc_NtkIsStrash( pNtk ) );
```
