### ISSUE TITLE
[PA1] Does number of fanouts includes POs?

### ISSUE THREAD

**Issue by tropurchan** [NTU-ALComLab/LSV-PA#397]
Suppose a node _u_ has 2 fanouts, one connecting to another internal node _v_, and the other connecting to some PO. Does _u_ lies in the MSFC of _v_?

**Comment by Luo-Yun-Rong** [comment]
> Suppose a node u has 2 fanouts, one connecting to another internal node v, and the other connecting to some PO. Does u lies in the MSFC of v?
No.
