### ISSUE TITLE
Run Well on macOS but get segmentation fault on Linux

### ISSUE THREAD

**Issue by Whyu1125** [NTU-ALComLab/LSV-PA#448]
As the title, my program not even prints ("###\n") out which I add in the void init(Abc_Frame_t* pAbc) {}.
I think that it's a big issue because TA might test it on Linux platform.
But I have no idea what's going on.
Thanks.

**Comment by Whyu1125** [comment]
And when I use grading script on Mac OS, it says that command not found.
But {pa_cmd} is lsv_or_bidec.
And I use it well if I directly run ./abc without script.

**Comment by Luo-Yun-Rong** [comment]
Could you post the screenshot of the command not found error？ Thanks

**Comment by Whyu1125** [comment]
<img width="683" alt="截圖 2021-12-21 下午6 08 12" src="https://user-images.githubusercontent.com/67723359/146911792-5ea93ef6-e17e-4d0b-9615-5b0a680336b8.png">

**Comment by Luo-Yun-Rong** [comment]
Please try this on MacOS terminal`brew install coreutils ` 
Could you also post the seg fault screenshot

**Comment by Whyu1125** [comment]
<img width="1834" alt="截圖 2021-12-21 下午6 14 50" src="https://user-images.githubusercontent.com/67723359/146912723-1463a6d3-85d3-4c3e-9ba3-f7ccd22e03de.png">

**Comment by Luo-Yun-Rong** [comment]
Please try to use debugger `gdb ` and see if you can figure out  the error.

**Comment by Whyu1125** [comment]
After installing it, it turns to segmentation fault as the figure above.
And I test the random_control/int2float.aig without script,  it doesn't lead to segmentation fault on macOS but on Linux.
OK Thanks. I would keep debugging

**Comment by Luo-Yun-Rong** [comment]
is the second figure on Mac or on linux.

**Comment by Whyu1125** [comment]
> Is the second figure on Mac or on linux？

It's on linux.
But it's the same on Mac after installing coreutils
And It's good if I directly run ./abc and read int2float.aig
<img width="1834" alt="截圖 2021-12-21 下午6 32 42" src="https://user-images.githubusercontent.com/67723359/146915358-70c7e63c-826a-4495-abf7-33e4798d44c0.png">

**Comment by Luo-Yun-Rong** [comment]
I think you have to figure out the issue by debugger. For mac, you can use the debugger `lldb`, for linux, you can use `gdb`. They are almost the same.

**Comment by Whyu1125** [comment]
I got 100 on linux after debugging.
But it still incurs segmentation fault only when I use grading script on Mac.
It doesn't allow me to use lldb on .sh
So I use lldb ./abc and read and lev_or_bidec for alll the files and it works well.
I wonder that if it's enough that the program can work well on linux platform.

**Comment by Whyu1125** [comment]
*lsv_or_bidec

**Comment by Luo-Yun-Rong** [comment]
Could you post your screenshot of seg fault error on Mac?

**Comment by Whyu1125** [comment]
![截圖 2021-12-22 上午11 34 35](https://user-images.githubusercontent.com/67723359/147031186-29082b35-4794-494e-ae7d-42b5c323ff36.png)

**Comment by Luo-Yun-Rong** [comment]
Can I see your `lsv_fall_2021/ref/arbiter.txt` and  `lsv_fall_2021/out/arbiter.txt` ?

**Comment by Whyu1125** [comment]
![截圖 2021-12-22 上午11 38 34](https://user-images.githubusercontent.com/67723359/147031505-52758446-29ce-4233-b52c-4f1301015ff3.png)

It seems to be the problem of use benchmarks as a substitute of EPFL benchmarks/folder
But I don't meet the problem when I test pa1 at that time.

**Comment by Luo-Yun-Rong** [comment]
Have you re-clone your repository since PA1, but forgotten to set the symbolic link to EPFL benchmark again? Under your repository, please run the following
```
ln -s  <your-path-to-EPFL-benchmark-suite> ./benchmarks
```

**Comment by Whyu1125** [comment]
I think it's the problem, and I can run it well now.
Sorry to bother you for the trivial issue.
Thank you very much.

**Comment by Luo-Yun-Rong** [comment]
Congrats! It's Okay.
