### ISSUE TITLE
Some questions about Pa1 problem4

### ISSUE THREAD

**Issue by jerry1249756** [NTU-ALComLab/LSV-PA#561]
1. Is it allowed to call the function 'Cudd_Eval'?
2. Is there any specification on the input pattern? Like the function y=a+b+c, is the input 001 meaning a,b,c  or b,a,c or other possible permutations, like the variable ordering in the BDD structure ?

**Comment by ghdftff542** [comment]
1. No
2. The variable order is the same as defined in the BLIF file. You can use "Abc_NtkForEachPi" to traverse all PIs.

**Comment by jerry1249756** [comment]
3. Is it possible to require the previous command be "collapse -x" instead of "collapse"? Since I could not find the input variable order after collapsing (it rewrites the entire network), or is there any hint on how to find the variable order (only the associated variables) of the collapsed network? Thanks!

**Comment by ghdftff542** [comment]
You should not assume that "collapse -x" is used. Here is a hint for finding the variable order: 
Since the "show_bdd" command shows the variable name of each decision level, 
you may look into the source code of that command to find some information.

**Comment by jerry1249756** [comment]
4. Is it allowed to modify the code outside ext-lsv/?

**Comment by ghdftff542** [comment]
4. No. 
We will only copy and paste the files inside *ext-lsv/* for grading.
