### ISSUE TITLE
PA1 problem 2

### ISSUE THREAD

**Issue by david057178-2020** [NTU-ALComLab/LSV-PA#73]
助教您好

請問PA1 第二題是要我們繳交一份文件檔
(a)用文字說明這四個指令差在哪裡
(b)把AIG轉SOP的指令依序列出來
就好了嗎?

其中(a)有提到要用four-bit adder當作例子，所以我們有需要繳交什麼程式跑出來的結果嗎?(print_stats或show生成的圖檔之類的)

謝謝解惑

**Comment by nianzelee** [comment]
> 請問PA1 第二題是要我們繳交一份文件檔
> (a)用文字說明這四個指令差在哪裡
> (b)把AIG轉SOP的指令依序列出來
> 就好了嗎?
> 

Yes, a short description is sufficient.


> 其中(a)有提到要用four-bit adder當作例子，所以我們有需要繳交什麼程式跑出來的結果嗎?(print_stats或show生成的圖檔之類的)
> 

No, you don't need to turn in any output generated by `ABC`.
Using the four-bit adder as an example to illustrate the difference is enough.
