### ISSUE TITLE
能否在abc project中新增檔案與資料夾

### ISSUE THREAD

**Issue by david057178-2020** [NTU-ALComLab/LSV-PA#75]
助教您好

針對PA1第三題，我們是不是只能將code寫在lsvCmd.cpp裡面阿?

因為我現在的做法是，在ext-lsv資料夾中額外新增了一個檔案叫print_sopunate.cpp，並將code實作在這個檔案內，當然同時也改寫了module.make所以整個abc在make之後能夠順利運作。

但是當我打git status後發現，他只有顯示我modified module.make，而沒有我新創的print_sopunate.cpp檔案，其他如add、commit、push也都找不到我新創的這個file。
我不確定這是不是因為當初這個project是從助教那邊fork過來的，所以我不能新增額外的檔案跟資料夾，而只能在現有的檔案做編輯。還是其實我只是應該調整什麼設定才能讓git抓到我新增的檔案呢?

謝謝解惑

**Comment by nianzelee** [comment]
Good observation.

I have updated this [wiki page](https://github.com/NTU-ALComLab/LSV-PA/wiki/Add-a-new-command) to answer your questions.

**Comment by nianzelee** [comment]
> 針對PA1第三題，我們是不是只能將code寫在lsvCmd.cpp裡面阿?

No, you can write the code anywhere you like.

> 我不確定這是不是因為當初這個project是從助教那邊fork過來的，所以我不能新增額外的檔案跟資料夾，而只能在現有的檔案做編輯。還是其實我只是應該調整什麼設定才能讓git抓到我新增的檔案呢?

No, it has nothing to do with forking. This is caused by file `.gitignore`.
