### ISSUE TITLE
unate在「用0表示的SOP」的定義

### ISSUE THREAD

**Issue by david057178-2020** [NTU-ALComLab/LSV-PA#76]
助教您好

我想確認一下unate在「用0表示的SOP」的定義
例如某個2-variable的node的SOP寫成下面這一行
00 0

表示他其實等價於
01 1
10 1
11 1

也就是這兩個variable都是binate對嗎?
謝謝

**Comment by nianzelee** [comment]
> 表示他其實等價於
> 01 1
> 10 1
> 11 1
> 
> 也就是這兩個variable都是binate對嗎?

The two variables are indeed binate with the above SOP.

However, the node is also equivalent to

```
1- 1
-1 1
```

And both variables are positive unate with respect to the above SOP.

I updated [PA1's readme](https://github.com/NTU-ALComLab/LSV-PA/blob/master/lsv/pa1/README.md) to resolve such ambiguity. Please take a look.
